version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: home-library-db
    environment:
      POSTGRES_DB: home_library
      POSTGRES_USER: home_library_user
      POSTGRES_PASSWORD: home_library_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U home_library_user -d home_library"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
